# Generated by Django 3.2.13 on 2022-05-09 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('schedule', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Schedule')),
                ('heart_pressure', models.CharField(max_length=20, verbose_name='Heart pressure')),
                ('glucose', models.CharField(max_length=20, verbose_name='Glucose')),
                ('observation', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Medical Evaluation',
                'verbose_name_plural': 'Medical Evaluations',
                'ordering': ('-schedule',),
            },
        ),
    ]
