# Generated by Django 3.2.13 on 2022-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicalevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('social_name', models.CharField(blank=True, max_length=80, verbose_name='Social Name')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('marital_status', models.IntegerField(choices=[(1, 'Married'), (2, 'Widowed'), (3, 'Separated'), (4, 'Divorced'), (5, 'Single')], verbose_name='Marital Status')),
                ('place_of_birth', models.CharField(blank=True, max_length=80, verbose_name='Place of Birth')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (0, '')], verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('observation', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ('name',),
            },
        ),
    ]
