# Generated by Django 3.2.13 on 2022-05-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevaluation',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_evaluations', to='medicine.patient'),
            preserve_default=False,
        ),
    ]
