# Generated by Django 3.2.13 on 2022-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicalevaluation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('coren', models.CharField(max_length=20, verbose_name='COREN')),
            ],
            options={
                'verbose_name': 'Nursing Professional',
                'verbose_name_plural': 'Nursing Professionals',
                'ordering': ('name',),
            },
        ),
    ]
