# Generated by Django 3.2.13 on 2022-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.ManyToManyField(to='medicine.Medicine'),
        ),
    ]
