# Generated by Django 3.2.13 on 2022-05-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicine', '0007_medication_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='observation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observation'),
        ),
    ]
