# Generated by Django 3.2.13 on 2022-05-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20220510_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='nursing_professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional'),
            preserve_default=False,
        ),
    ]
