# Generated by Django 3.2.13 on 2022-05-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_medication_nursing_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalevaluation',
            name='nursing_professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional', verbose_name='Nursing Professional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.ManyToManyField(to='medicine.Medicine', verbose_name='Medicines'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='nursing_professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional', verbose_name='Nursing Professional'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.patient', verbose_name='Patient'),
        ),
    ]
