# Generated by Django 3.2.13 on 2022-05-17 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0016_auto_20220515_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingProfessionalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(blank=True,
                 default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(blank=True,
                 max_length=80, null=True, verbose_name='Name')),
                ('coren', models.CharField(blank=True,
                 max_length=20, null=True, verbose_name='COREN')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='medicine_nursingprofessionalhistory_related_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='medicine_nursingprofessionalhistory_related_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='Deactivated by')),
                ('nursing_professional', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='medicine_nursingprofessionalhistory_related_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Nursing Professional History',
                'verbose_name_plural': 'Nursing Professional Histories',
                'ordering': ('-id',),
            },
        ),
    ]
