# Generated by Django 3.2.13 on 2022-05-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0017_nursingprofessionalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevaluation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.patient'),
        ),
        migrations.CreateModel(
            name='MedicalEvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('schedule', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Schedule')),
                ('heart_pressure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Heart pressure')),
                ('glucose', models.CharField(blank=True, max_length=20, null=True, verbose_name='Glucose')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicalevaluationhistory_related_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicalevaluationhistory_related_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='Deactivated by')),
                ('medical_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicalevaluation', verbose_name='Medical Evaluation')),
                ('nursing_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional', verbose_name='Nursing Professional')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_evaluations', to='medicine.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicalevaluationhistory_related_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Medical Evaluation History',
                'verbose_name_plural': 'Medical Evaluations Histories',
                'ordering': ('-schedule',),
            },
        ),
    ]
