# Generated by Django 3.2.13 on 2022-05-18 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0018_auto_20220517_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalevaluation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='medicine.patient', verbose_name='Patient'),
        ),
    ]
