# Generated by Django 3.2.13 on 2022-05-21 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0019_alter_medicalevaluation_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalevaluation',
            options={'ordering': ('-is_active', '-schedule'), 'verbose_name': 'Medical Evaluation', 'verbose_name_plural': 'Medical Evaluations'},
        ),
        migrations.AlterModelOptions(
            name='medicalevaluationhistory',
            options={'ordering': ('-id',), 'verbose_name': 'Medical Evaluation History', 'verbose_name_plural': 'Medical Evaluations Histories'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ('-is_active', '-schedule'), 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='nursingprofessional',
            options={'ordering': ('-is_active', 'name'), 'verbose_name': 'Nursing Professional', 'verbose_name_plural': 'Nursing Professionals'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-is_active', 'name'), 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('schedule', models.DateTimeField(blank=True, null=True, verbose_name='Schedule')),
                ('observation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicationhistory_related_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicationhistory_related_deactivated_by', to=settings.AUTH_USER_MODEL, verbose_name='Deactivated by')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medication', verbose_name='Medication')),
                ('medicine', models.ManyToManyField(to='medicine.Medicine', verbose_name='Medicines')),
                ('nursing_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.nursingprofessional', verbose_name='Nursing Professional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_medicationhistory_related_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Medication History',
                'verbose_name_plural': 'Medication Histories',
                'ordering': ('-is_active', '-schedule'),
            },
        ),
    ]
